config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :movies
    resources :categories
    resources :reviews

    root to: 'users#index'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :movies, only: %i[index show]
  resource :about, only: %i[show]
  resource :review, only: %i[create]
  resources :categories, only: %i[show]

  root 'home#index'
end

app/views/layouts/partials/_alerts.haml
- if notice
    %p.notice.alert.alert-success{id: 'notice_message'}= notice
- elsif alert
    %p.alert.alert-danger{id: 'alert_message'}= alert

app/views/layouts/partials/_banner.haml
%header.bg-dark.py-5
  .container.px-4.px-lg-5.my-5
    .text-center.text-white
      %h1.display-4.fw-bolder
        = current_page?(root_path) ? I18n.t(:'banner.home_page') : @category.name
      - if !current_user
        %p.lead.fw-normal.text-white-50.mb-0 #{I18n.t(:'banner.login')}

app/views/layouts/partials/_footer.haml
%footer.py-5.bg-dark.mt-auto
  .container
    %p.m-0.text-center.text-white #{I18n.t(:footer_label)}

app/views/layouts/partials/_header.haml
%header
  = render partial: 'layouts/partials/alerts'
  %nav.navbar.navbar-expand-lg.navbar-light.bg-light
    .container.px-4.px-lg-5
      =link_to I18n.t(:brand), root_path, data: {turbo:false}, class: 'navbar-brand'
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", type: "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0.ms-lg-4
          %li.nav-item
            =link_to I18n.t(:'navbar.home_btn_text'), root_path, data: {turbo:false}, id: 'home_link_header', class: request.path == root_path ? 'nav-link active' : 'nav-link'
          %li.nav-item
            =link_to I18n.t(:'navbar.about_btn_text'), about_path, data: {turbo:false}, class: request.path == about_path ? 'nav-link active' : 'nav-link'
          - if current_user
            %li.nav-item.dropdown
              %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", href: "#", role: "button"} #{I18n.t(:'navbar.account_btn_text')}
              %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
                %li
                  = link_to I18n.t(:'navbar.settings_btn_text'), edit_user_registration_path, data: {turbo:false}, class: 'dropdown-item'
            - if current_user.admin?
              %li.nav-item
                =link_to I18n.t(:'navbar.administrate_btn_text'), admin_root_path, data: {turbo:false}, class: 'nav-link'
        %form.d-flex
          - if current_user
            = link_to I18n.t(:'navbar.log_out_btn_text'), destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-outline-dark', id: 'logout_btn'
          - else
            = link_to I18n.t(:'navbar.log_in_btn_text'), new_user_session_path, data: {turbo:false}, class: 'btn btn-outline-dark', id: 'login_btn'